=== Ayoub-BL/Projet_AMU_XML_XQuery/master.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT master 				(intervenants,parcours*)>

<!ELEMENT intervenants 			(intervenant+)>

<!ELEMENT intervenant 			(nom,adresse)>
<!ATTLIST intervenant 			id				ID		#REQUIRED>

<!ELEMENT nom 					(#PCDATA)>
<!ELEMENT adresse 				(mail | site_web)*>
<!ELEMENT mail 					(#PCDATA)>
<!ELEMENT site_web 				(#PCDATA)>

<!ELEMENT parcours 				(nom,lieu+,responsable+,description?,semestre+,debouches?)>
<!ATTLIST parcours 				code			ID		#REQUIRED>

<!ELEMENT lieu 					(#PCDATA)>

<!ELEMENT responsable 			(#PCDATA)>
<!ATTLIST responsable 			ref				IDREF	#REQUIRED>

<!ELEMENT description 			(texte)>
<!ELEMENT semestre 				(unites_obligatoires,unites_optionnelles*)>
<!ATTLIST semestre 				id 				(S1 | S2 | S3 | S4 | S5 | S6) 		#REQUIRED>

<!ELEMENT debouches 			(texte)>

<!ELEMENT texte 				(#PCDATA | ul | p | table | a | b)*>
<!ELEMENT ul 					(li+,ul*)>
<!ELEMENT li 					(#PCDATA)>
<!ELEMENT p 					(#PCDATA | b | i | a)*>
<!ELEMENT table 				(th*, tr*)>
<!ELEMENT th					(#PCDATA)>
<!ELEMENT tr 					(td*)>
<!ELEMENT td 					(#PCDATA)>
<!ELEMENT b 					(#PCDATA)>
<!ELEMENT i 					(#PCDATA)>
<!ELEMENT a 					ANY>
<!ATTLIST a  					href			CDATA	#REQUIRED>

<!ELEMENT unites_obligatoires 	(unite+)>

<!ELEMENT unites_optionnelles 	(unite+)>
<!ATTLIST unites_optionnelles 	credits_options	CDATA	#REQUIRED>

<!ELEMENT unite 				(nom,credits,ref_intervenant+,resume,plan?,lieu?)>
<!ATTLIST unite					id 				(ENSINAU1 | ENSINAU10 | ENSINAU12 | ENSINAU13 | ENSINAU2 | ENSINAU3 | ENSINAU4 | ENSINAU6 | ENSINAU7 | ENSINAU8 | ENSINAU9 | ENSINBU1 | ENSINBU10 | ENSINBU11 | ENSINBU12 | ENSINBU13 | ENSINBU15 | ENSINBU16 | ENSINBU2 | ENSINBU4 | ENSINBU5 | ENSINBU6 | ENSINBU7 | ENSINBU8 | ENSINBU9 | ENSINCU1 | ENSINCU10 | ENSINCU11 | ENSINCU12 | ENSINCU13 | ENSINCU14 | ENSINCU15 | ENSINCU16 | ENSINCU17 | ENSINCU18 | ENSINCU19 | ENSINCU2 | ENSINCU20 | ENSINCU21 | ENSINCU22 | ENSINCU23 | ENSINCU24 | ENSINCU25 | ENSINCU26 | ENSINCU27 | ENSINCU28 | ENSINCU29 | ENSINCU3 | ENSINCU30 | ENSINCU31 | ENSINCU32 | ENSINCU33 | ENSINCU34 | ENSINCU35 | ENSINCU36 | ENSINCU37 | ENSINCU38 | ENSINCU39 | ENSINCU4 | ENSINCU40 | ENSINCU41 | ENSINCU42 | ENSINCU43 | ENSINCU44 | ENSINCU45 | ENSINCU46 | ENSINCU47 | ENSINCU48 | ENSINCU49 | ENSINCU5 | ENSINCU50 | ENSINCU53 | ENSINCU54 | ENSINCU56 | ENSINCU58 | ENSINCU59 | ENSINCU6 | ENSINCU60 | ENSINCU64 | ENSINCU65 | ENSINCU66 | ENSINCU67 | ENSINCU68 | ENSINCU69 | ENSINCU7 | ENSINCU72 | ENSINCU73 | ENSINCU74 | ENSINCU75 | ENSINCU8 | ENSINCU9 | ENSINDU1 | ENSINDU2 | ENSINDU3 | ENSINDU4 | ENSISCU1 | ENSISCU2 | ENSISCU20 | ENSISCU21 | ENSISCU22 | ENSISCU23 | ENSISCU24 | ENSISCU25 | ENSISCU26 | ENSISCU27 | ENSISCU28 | ENSISCU29 | ENSISCU3 | ENSISCU30 | ENSISCU31 | ENSISCU32 | ENSISCU33 | ENSISCU34 | ENSISCU35 | ENSISCU36 | ENSISCU37 | ENSISCU38 | ENSISCU39 | ENSISCU4 | ENSISCU40 | ENSISCU41 | ENSISCU42 | ENSISCU43 | ENSISCU44 | ENSISCU45 | ENSISCU46 | ENSISCU5 | ENSISCU55 | ENSISCU6 | ENSISCU7 | ENSISCU8 | ENSISDU3 | ENSISDU4)	  #REQUIRED>

<!ELEMENT ref_intervenant 		ANY>
<!ATTLIST ref_intervenant 		ref				IDREF	#IMPLIED>

<!ELEMENT credits 				(#PCDATA)>
<!ELEMENT resume 				(texte)?>
<!ELEMENT plan 					(nbrCours,nbrTD?,nbrTP?)>

<!ELEMENT nbrCours 				(#PCDATA)>
<!ELEMENT nbrTD 				(#PCDATA)>
<!ELEMENT nbrTP 				(#PCDATA)>

=== Ayoub-BL/Projet_AMU_XML_XQuery/master_with_entities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master SYSTEM "master.dtd"[
		<!ENTITY dom.mail-mrs "univ-mrs.fr">
		<!ENTITY dom.mail-amu "univ-amu.fr">
		<!ENTITY dom.lieu-luminy "Luminy">
		<!ENTITY dom.lieu-saint-jerome "Saint-Jérôme">
]>
<master>
	<intervenants>
		<intervenant id="Remi_MORIN">
			<nom>Rémi MORIN</nom>
			<adresse>
				<mail>remi.morin@&dom.mail-amu;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~remi.morin/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Jean-Luc_MASSAT">
			<nom>Jean-Luc MASSAT</nom>
			<adresse>
				<mail>jean-luc.massat@&dom.mail-amu;</mail>
				<site_web>http://jean-luc.massat.perso.luminy.&dom.mail-amu;</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Magali_CONTENSIN">
			<nom>Magali CONTENSIN</nom>
			<adresse>
				<mail>Magali.Contensin@&dom.mail-mrs;</mail>
				<site_web>http://magali.contensin.free.fr/html/InternetLicPro.html</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Nadia_CREIGNOU">
			<nom>Nadia CREIGNOU</nom>
			<adresse>
				<mail>nadia.creignou@&dom.mail-amu;</mail>
				<site_web>http://www.lif.&dom.mail-mrs;/annuaire/personne/1155937</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Frederic_OLIVE">
			<nom>Frederic OLIVE</nom>
			<adresse>
				<mail>frederic.olive@lif.&dom.mail-mrs;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~frederic.olive/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Pablo_ARRIGHI">
			<nom>Pablo ARRIGHI</nom>
			<adresse>
				<mail>pablo.ARRIGHI@&dom.mail-amu;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~pablo.arrighi/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Kevin_PERROT">
			<nom>Kevin PERROT</nom>
			<adresse>
				<mail>kevin.perrot@lif.&dom.mail-mrs;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~kevin.perrot/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Djamal_HABET">
			<nom>Djamal HABET</nom>
			<adresse>
				<mail>djamal.habet@&dom.mail-amu;</mail>
				<site_web>http://www.lsis.org/habetd/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Frederic_BECHET">
			<nom>Frederic BECHET</nom>
			<adresse>
				<mail>frederic.bechet@&dom.mail-amu;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~frederic.bechet/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Omar_BOUCELMA">
			<nom>Omar BOUCELMA</nom>
			<adresse>
				<mail>omar.boucelma@&dom.mail-amu;</mail>
				<site_web>https://annuaire.&dom.mail-amu;/personnel/detail/b21hci5ib3VjZWxtYQ==</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Nicola_OLIVETTI">
			<nom>Nicola OLIVETTI</nom>
			<adresse>
				<mail>nicola.olivetti@&dom.mail-amu;</mail>
				<site_web>http://www.lsis.org/olivetti/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Pierre-Alain_REYNIER">
			<nom>Pierre-Alain REYNIER</nom>
			<adresse>
				<mail>pierre-alain.reynier@&dom.mail-amu;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~pierre-alain.reynier/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Luigi_SANTOCANALE">
			<nom>Luigi SANTOCANALE</nom>
			<adresse>
				<mail>luigi.santocanale@&dom.mail-amu;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~luigi.santocanale/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Lydie_RENE-CHABAROT">
			<nom>Lydie Réné-CHABAROT</nom>
			<adresse>
				<mail>lydie.rene@&dom.mail-amu;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~luigi.santocanale/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Emmanuel_GODARD">
			<nom>Emmanuel GODARD</nom>
			<adresse>
				<mail>emmanuel.godard@&dom.mail-amu;</mail>
				<site_web>http://pageperso.lif.&dom.mail-mrs;/~emmanuel.godard/</site_web>
			</adresse>
		</intervenant>
		<intervenant id="Noel_NOVELLI">
			<nom>Noël Novelli</nom>
			<adresse>
				<mail>noel.novelli@&dom.mail-amu;</mail>
			</adresse>
		</intervenant>
		<intervenant id="Thierry_ARTIERES">
			<nom>Thierry ARTIERES</nom>
			<adresse>
				<site_web>thierry.artieres@lif.univ-mrs.fr</site_web>
			</adresse>
		</intervenant>
	</intervenants>	
	<parcours code="M1">
		<nom>Première année de tronc commun</nom>
		<lieu>&dom.lieu-luminy;</lieu>
		<lieu>&dom.lieu-saint-jerome;</lieu>
		<responsable ref="Remi_MORIN"/>
		<description>
			<texte>
				<p>L'objectif de cette première année est de donner les bases indispensables permettant, en deuxième année, de choisir une spécialisation dans un domaine précis. Sur les 60 crédits de cette première année, 15 crédits correspondent à des enseignements optionnels. Ces options permettent de construire un parcours adapté. Un choix entre stage ou projet encadré est également proposé au semestre de printemps.</p>
			</texte>
		</description>
		<semestre id="S1">	
			<unites_obligatoires>
				<unite id="ENSINAU1">
					<nom>Génie Logiciel</nom>
					<credits>6</credits>
					<ref_intervenant ref="Pablo_ARRIGHI"/>
					<ref_intervenant ref="Kevin_PERROT"/>
					<resume>
						<texte>
							<ul>
							    <li>Processus logiciel</li>
							    <li>Gestion de projet</li>
							    <li>Spécification et conception (artefact : notation UML)</li>
							    <li>Design patterns</li>
							</ul>
						</texte>
					</resume>
					<plan>
						 <nbrCours>20</nbrCours>
						 <nbrTD>20</nbrTD>
						 <nbrTP>20</nbrTP>
					</plan>
					<lieu>&dom.lieu-luminy;</lieu>
				</unite>		
				<unite id="ENSINAU2">
					<nom>Complexité</nom>
					<credits>6</credits>
					<ref_intervenant ref="Nadia_CREIGNOU"/>
					<ref_intervenant ref="Frederic_OLIVE"/>
					<resume>
						<texte>
							<ul>
							    <li>Rappels sur les notions d'analyse de la complexité des algorithmes et des problèmes.</li>
							    <li>Notion de problèmes (décision, recherche, dénombrement, énumération, optimisation). Bornes inférieures de complexité.</li>
							    <li>Classes P et NP. Problèmes NP-complets.</li>
							    <li>Méthodes de résolution des problèmes NP-Complets.</li>
							</ul>
						</texte>
					</resume>
					<plan>
						 <nbrCours>20</nbrCours>
						 <nbrTD>20</nbrTD>
						 <nbrTP>20</nbrTP>
					</plan>
					<lieu>&dom.lieu-luminy;</lieu>
				</unite>			
				<unite id="ENSINAU3">
					<nom>Réseaux</nom>
					<credits>6</credits>
					<ref_intervenant ref="Emmanuel_GODARD"/>
					<resume>
						<texte>
							<ul>
							    <li>Architecture en couches, standard OSI</li>
							    <li>Couche physique</li>
							    <li>Couche liaison de Données</li>
							    <li>Réseau IP</li>
							    <li>Algorithmes de routage, routage IP</li>
							    <li>Protocole TCP/IP</li>
							    <li>Couche Application : HTTP, SMTP, FTP, ...</li>
							    <li>Bases des protocoles cryptographiques (terminologie, architecture à clef publique).</li>
							    <li>Introduction à la Sécurité des réseaux.</li>
							</ul>
						</texte>
					</resume>
					<plan>
						 <nbrCours>20</nbrCours>
						 <nbrTD>20</nbrTD>
						 <nbrTP>20</nbrTP>
					</plan>
					<lieu>&dom.lieu-luminy;</lieu>
				</unite>
				<unite id="ENSINAU4">
					<nom>Programmation fonctionnelle</nom>
					<credits>3</credits>
					<ref_intervenant ref="Luigi_SANTOCANALE"/>
					<resume>
						<texte>
							<ul>
								<li>1- Introduction à la programmation fonctionnelle, sur l'exemple du langage  OCaml Expressions, évaluation, types de base. Polymorphisme, ordre supérieur. Fonctions récursives, filtrage. Les diverses stratégies d'évaluation, application à la programmation d'un opérateur de point fixe.</li>
							    <li>2- Les types Sommes, types récursifs, polymorphes. Arbres. Filtrage.</li>
								<li>3- Sémantique opérationnelle Liaisons, environnements, clôtures. Évaluation des fonctions récursives .</li>
								<li>4- Aspects impératifs Exceptions, entrées-sorties, séquencement, fichiers, références, tableaux, enregistrements.</li>
								<li>5- Implantation du filtrage en OCaml Termes formels, substitutions, filtrage.</li>
							</ul>
						</texte>
					</resume>
					<plan>
						 <nbrCours>20</nbrCours>
						 <nbrTD>20</nbrTD>
						 <nbrTP>20</nbrTP>
					</plan>
					<lieu>&dom.lieu-luminy;</lieu>
				</unite>
				<unite id="ENSINAU12">
					<nom>BDR : approfondissement</nom>
					<credits>3</credits>
					<ref_intervenant ref="Remi_MORIN"/>
					<resume>
						<texte>
							<p>nous sommes désolé, mais nous n'avons pas encore de resume.</p>
						</texte>
					</resume>
					<plan>
						 <nbrCours>10</nbrCours>
						 <nbrTD>10</nbrTD>
						 <nbrTP>10</nbrTP>
					</plan>
					<lieu>&dom.lieu-luminy;</lieu>
				</unite>
			</unites_obligatoires>
			<unites_optionnelles credits_options="6">
				<unite id="ENSINAU6">
					<nom>Programmation logique</nom>
					<credits>3</credits>
					<ref_intervenant ref="Remi_MORIN"/>
					<resume>
						<texte>
							<ul>
								<li>Introduction. Forme générale des règles. Effacement, unification, backtracking. Contrôle de l'exécution.</li>
								<li>Listes, arbres et n-uplets. Liste représentée par différence de listes. Ajout en tête et en queue, concaténation.</li>
								<li>Analyseurs syntaxiques. Construction d'un arbre syntaxique. Liste des feuilles d'un arbre. Freeze et analyse par feuille.</li>
								<li>Règles prédéfinies</li>
							</ul>
						</texte>
					</resume>
					<plan>
						 <nbrCours>10</nbrCours>
						 <nbrTD>10</nbrTD>
						 <nbrTP>10</nbrTP>
					</plan>
					<lieu>&dom.lieu-luminy;</lieu>
				</unite>
				<unite id="ENSINAU7">
					<nom>Outils de l'internet</nom>
					<credits>3</credits>
					<ref_intervenant ref="Magali_CONTENSIN"/>
					<resume>
						<texte>
							<ul>
							    <li>Présentation d'Internet.</li>
							    <li>Les langages et les normes sur Internet.</li>
							    <li>Les protocoles : HTTP, HTTP, SMTP, IMAP, POP3</li>
							    <li>Les applications site_web.</li>
							    <li>Sécurité.</li>
							    <li>Les nouvelles et futures technologies.</li>
							</ul>
						</texte>
					</resume>
					<plan>
